
server:
  port: 8761
  
spring:
  application:
    name: discovery-server
    
eureka:
  instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 2
      lease-expiration-duration-in-seconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    
    